version: '2'
services:
    app4-app:
        image: app4
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://app4-postgresql:5432/app4
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    app4-postgresql:
        extends:
            file: postgresql.yml
            service: app4-postgresql
